name: MultiMaintenance
version: '${project.version}'
main: me.capitainecat0.multimaintenance.MultiMaintenance
api-version: 1.13
authors: [ CapitaineCat0, It'sTheSky ]
description: Plugin de maintenance de HOG
commands:
  maintenance:
    description: Gèrer la maintenance du serveur
    aliases:
      - maint
      - multimaintenance
      - multimaint
      - multim
      - maintenance
      - mm
